"""add cardio sessions

Revision ID: 14b873077b82
Revises: 6a5a2eec8980
Create Date: 2026-06-17 00:44:07.661066
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b873077b82'
down_revision: Union[str, None] = '6a5a2eec8980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardio_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('run_type', sa.Enum('EASY', 'TEMPO_INTERVAL', 'LONG', name='runtype', native_enum=False), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('average_pace', sa.Float(), nullable=False),
    sa.Column('body_weight_used', sa.Float(), nullable=False),
    sa.Column('estimated_calories', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cardio_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cardio_sessions'))
    )
    with op.batch_alter_table('cardio_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cardio_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardio_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cardio_sessions_user_id'))

    op.drop_table('cardio_sessions')
    # ### end Alembic commands ###