"""add meals domain

Revision ID: 6a5a2eec8980
Revises: 7ab91acf684d
Create Date: 2026-06-16 00:53:45.535023
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5a2eec8980'
down_revision: Union[str, None] = '7ab91acf684d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_nutrition_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_nutrition_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_nutrition_logs')),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_logs_user_date')
    )
    with op.batch_alter_table('daily_nutrition_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_nutrition_logs_user_id'), ['user_id'], unique=False)

    op.create_table('food_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('calories_per_unit', sa.Float(), nullable=False),
    sa.Column('protein_per_unit', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_food_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_items'))
    )
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.create_index('ix_food_items_global_name_unit', ['name', 'unit'], unique=True, sqlite_where=sa.text('user_id IS NULL'))
        batch_op.create_index(batch_op.f('ix_food_items_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_food_items_user_name_unit', ['user_id', 'name', 'unit'], unique=True, sqlite_where=sa.text('user_id IS NOT NULL'))

    op.create_table('meal_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_templates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_templates')),
    sa.UniqueConstraint('user_id', 'name', name='uq_meal_templates_user_name')
    )
    with op.batch_alter_table('meal_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_templates_user_id'), ['user_id'], unique=False)

    op.create_table('recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    sa.UniqueConstraint('user_id', 'name', name='uq_recipes_user_name')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_user_id'), ['user_id'], unique=False)

    op.create_table('daily_nutrition_log_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('entry_name', sa.String(length=255), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['daily_nutrition_logs.id'], name=op.f('fk_daily_nutrition_log_entries_log_id_daily_nutrition_logs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_nutrition_log_entries'))
    )
    with op.batch_alter_table('daily_nutrition_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_nutrition_log_entries_log_id'), ['log_id'], unique=False)

    op.create_table('meal_template_foods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meal_template_id', sa.String(length=36), nullable=False),
    sa.Column('food_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], name=op.f('fk_meal_template_foods_food_item_id_food_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meal_template_id'], ['meal_templates.id'], name=op.f('fk_meal_template_foods_meal_template_id_meal_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_template_foods'))
    )
    with op.batch_alter_table('meal_template_foods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_template_foods_food_item_id'), ['food_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_template_foods_meal_template_id'), ['meal_template_id'], unique=False)

    op.create_table('meal_template_recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meal_template_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['meal_template_id'], ['meal_templates.id'], name=op.f('fk_meal_template_recipes_meal_template_id_meal_templates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_meal_template_recipes_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_template_recipes'))
    )
    with op.batch_alter_table('meal_template_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_template_recipes_meal_template_id'), ['meal_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_template_recipes_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('recipe_ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('food_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_items.id'], name=op.f('fk_recipe_ingredients_food_item_id_food_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_ingredients_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients')),
    sa.UniqueConstraint('recipe_id', 'food_item_id', name='uq_recipe_ingredients_recipe_food')
    )
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_food_item_id'), ['food_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('daily_nutrition_log_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_nutrition_log_entries.id'], name=op.f('fk_daily_nutrition_log_items_entry_id_daily_nutrition_log_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_nutrition_log_items'))
    )
    with op.batch_alter_table('daily_nutrition_log_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_nutrition_log_items_entry_id'), ['entry_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_nutrition_log_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_nutrition_log_items_entry_id'))

    op.drop_table('daily_nutrition_log_items')
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_food_item_id'))

    op.drop_table('recipe_ingredients')
    with op.batch_alter_table('meal_template_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_template_recipes_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_meal_template_recipes_meal_template_id'))

    op.drop_table('meal_template_recipes')
    with op.batch_alter_table('meal_template_foods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_template_foods_meal_template_id'))
        batch_op.drop_index(batch_op.f('ix_meal_template_foods_food_item_id'))

    op.drop_table('meal_template_foods')
    with op.batch_alter_table('daily_nutrition_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_nutrition_log_entries_log_id'))

    op.drop_table('daily_nutrition_log_entries')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_user_id'))

    op.drop_table('recipes')
    with op.batch_alter_table('meal_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_templates_user_id'))

    op.drop_table('meal_templates')
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_index('ix_food_items_user_name_unit', sqlite_where=sa.text('user_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_food_items_user_id'))
        batch_op.drop_index('ix_food_items_global_name_unit', sqlite_where=sa.text('user_id IS NULL'))

    op.drop_table('food_items')
    with op.batch_alter_table('daily_nutrition_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_nutrition_logs_user_id'))

    op.drop_table('daily_nutrition_logs')
    # ### end Alembic commands ###